listen-to-story
daniel-bergmann/german-stories pull request #5
Opened 2024-12-30 20:35 UTC by mohsenkhosroanjam

2025-01-05 11:59 UTC, daniel-bergmann requested changes
The JS is getting cluttered as we are building the app so maybe we should start to modularize the JS code into seperate directories. Could you add the JS code for the voiceover into a new file inside of a "js" directory?

That way the code is easier to maintain

2025-01-05 12:19 UTC, mohsenkhosroanjam commented
Sure! will work on it and the comments you provided in the issue. I will try to get back to you soon.

2025-01-08 14:08 UTC, mohsenkhosroanjam commented
Hi @daniel-bergmann , done!

2025-01-14 09:52 UTC, mohsenkhosroanjam commented
@daniel-bergmann Hi dude, I just wanted to remind you that my PR has been updated for your review.
I hope you are doing well.

2025-01-15 19:12 UTC, merged

2025-01-15 19:12 UTC, daniel-bergmann commented
Great work! well done!